[tool.poetry]
name = "spybot2"
version = "0.1.0"
description = ""
authors = ["Benno <bensge@me.com>", "Justus <justus.fab@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.1.4"
ts3 = "2.0.0b3"
django-environ = "^0.9.0"
mysqlclient = "^2.1.1"
django-crontab = "^0.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
